
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - files:
      - application.properties=app-config/application.properties
    name: cos-fleetshard-sync-config

resources:
  - ./kubernetes.yml
  - ./observability
  - ./crds