apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: cos-fleetshard-sync
  name: cos-fleetshard-sync
spec:
  endpoints:
    - interval: 30s
      path: /q/metrics
      port: http
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: cos-fleetshard-sync
