
generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: cos-fleetshard-operator-camel-config
    files:
      - application.properties=app-config/application.properties

resources:
  - ./kubernetes.yml
